// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Loader } from "./Loader";

export interface Instance { name: string, game_version: string, path?: string, loader: Loader, }