// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Artifact } from "./Artifact";
import type { LocaleKey } from "./LocaleKey";
import type { ModCategory } from "./ModCategory";
import type { ModLocale } from "./ModLocale";

export interface MetaMod { id: string, version: string, optional: boolean, artifact: Artifact, recommended: boolean, category: ModCategory, locale: Record<LocaleKey, ModLocale>, }