// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Artifact } from "./Artifact";

export interface MetaFile { path: string, validate: boolean, artifact: Artifact, }